const express = require('express');
const Post = require('../models/Post');
const Category = require('../models/Category');
const router = express.Router();
const { upload, cloudinary } = require('../utils/cloudinary');

const { protect } = require('../middleware/authMiddleware');
const authorizeRole = require('../middleware/authRole');
const fakeAuth = require('../middleware/fakeAuth');

// Helper function to resolve category name/ID to ObjectId
const resolveCategory = async (categoryValue) => {
  if (!categoryValue || (typeof categoryValue === 'string' && !categoryValue.trim())) {
    throw new Error('Category is required');
  }

  try {
    // Check if it's already a valid MongoDB ObjectId
    const mongoose = require('mongoose');
    if (mongoose.Types.ObjectId.isValid(categoryValue)) {
      // It's an ObjectId - check if category exists
      const existingById = await Category.findById(categoryValue);
      if (existingById) {
        return categoryValue;
      }
    }
    
    // Try to find existing category by name
    let category = await Category.findOne({ name: categoryValue });
    
    if (!category) {
      // Create new category if it doesn't exist
      // The slug will be auto-generated by the pre-save hook
      category = await Category.create({ 
        name: categoryValue,
        description: `Posts related to ${categoryValue}`
      });
      console.log(`Created new category: ${categoryValue} with slug: ${category.slug}`);
    }
    
    return category._id;
  } catch (error) {
    console.error('Error resolving category:', error);
    throw new Error(`Failed to resolve category: ${error.message}`);
  }
};

// GET /api/posts - Get/list all posts
router.get('/', async (req, res) => {
    try {
        const {
            category,
            author,
            tag,
            sort = '-createdAt',
            page = 1,
            limit = 10,
            select = 'title slug excerpt featuredImage category author viewCount createdAt updatedAt',
        } = req.query;

        const query = {};
        if (category) query.category = category;
        if (author) query.author = author;
        if (tag) query.tags = { $in: [tag] };

        const pageNumber = parseInt(page, 10);
        const pageSize = parseInt(limit, 10);
        const skip = (pageNumber - 1) * pageSize;

        const posts = await Post.find(query)
            .select(select)
            .populate('category', 'name slug')
            .populate('author', 'name email')
            .sort(sort)
            .skip(skip)
            .limit(pageSize);
        
        const totalPosts = await Post.countDocuments(query);


        res.status(200).json({
            success: true,
            count: posts.length,
            total: totalPosts,
            page: pageNumber,
            data: posts,
            totalPages: Math.ceil(totalPosts / pageSize),
        });
    } catch (error) {
        console.error(error);
        res.status(500).json({
            success: false,
            error: error.message || 'Server Error'
        });
    }
});

// GET /api/posts/slug/:slug - Get a specific blog post by slug (for external apps)
router.get('/slug/:slug', async (req, res) => {
    try {
        const { slug } = req.params;

        const post = await Post.findOne({ slug })
            .populate('category', 'name slug')
            .populate('author', 'name email');
        
        if (!post) {
            return res.status(404).json({
                success: false,
                error: 'Blog post does not exist',
            });
        }

        // Increment view count
        post.viewCount += 1;
        await post.save();

        res.status(200).json({
            success: true,
            data: post,
        });
    } catch (error) {
        console.error(error);
        res.status(500).json({
            success: false,
            error: error.message
        });
    }
});

// GET /api/posts/:idOrSlug - Get a specific blog post by ID or slug
router.get('/:idOrSlug', async (req, res) => {
    try {
        const { idOrSlug } = req.params;

        // Try to find by slug first, then by ObjectId
        let post = await Post.findOne({ slug: idOrSlug })
            .populate('category', 'name slug')
            .populate('author', 'name email');
        
        // If not found by slug, try by ID
        if (!post) {
            post = await Post.findById(idOrSlug)
                .populate('category', 'name slug')
                .populate('author', 'name email');
        }
        
        if (!post) {
            return res.status(404).json({
                success: false,
                error: 'Blog post does not exist',
            });
        }

        // Increment view count
        post.viewCount += 1;
        await post.save();

        res.status(200).json({
            success: true,
            data: post,
        });
    } catch (error) {
        console.error(error);
        res.status(500).json({
            success: false,
            error: error.message
        });
    }
});

// POST /api/posts/ - Create a new blog post
router.post('/', fakeAuth, async (req, res) => {
    try {
        const { title, content, author, category, featuredImage, excerpt, tags, isPublished } = req.body;

        console.log('Received category:', category, 'type:', typeof category);

        // Use authenticated user ID if available, otherwise use provided author
        const authorId = req.user ? req.user._id : author;

        // Resolve category name to ObjectId only if category is provided
        let categoryId = null;
        if (category && category.trim()) {
          categoryId = await resolveCategory(category);
        } else if (isPublished) {
          // If publishing, category is required
          throw new Error('Category is required');
        }

        const newPost = new Post({
            title,
            content,
            author: authorId,
            category: categoryId,
            featuredImage,
            excerpt,
            tags,
            isPublished,
        });

        const savedPost = await newPost.save();
        res.status(201).json({
            success: true,
            data: savedPost,
        });
    } catch (error) {
        console.error('Post creation error:', error);
        res.status(500).json({
            success: false,
            error: error.message || 'Server Error'
        });
    }
});

// PUT /api/posts/:idOrSlug - Update an existing blog post by ID or slug
router.put('/:idOrSlug', fakeAuth, async (req, res) => {
    try {
        const { idOrSlug } = req.params;
        const updateData = { ...req.body };

        // Use authenticated user ID if available
        if (req.user) {
            updateData.author = req.user._id;
        }

        // Resolve category name to ObjectId if category is being updated
        if (updateData.category === null || updateData.category === "") {
          // Allow clearing category if explicitly set to null
          delete updateData.category;
        } else if (updateData.category && updateData.category.trim()) {
          // Only resolve if it's a non-empty string
          const resolvedCat = await resolveCategory(updateData.category);
          updateData.category = resolvedCat;
        } else if (updateData.isPublished) {
          // If publishing without category, throw error
          const currentPost = await Post.findOne({ slug: idOrSlug });
          if (!currentPost?.category) {
            throw new Error('Category is required');
          }
          delete updateData.category;
        }

        // Find by slug first, then by ID
        let updatedPost = await Post.findOneAndUpdate({ slug: idOrSlug }, updateData, {
            new: true,
            runValidators: true,
        });

        // If not found by slug, try by ID
        if (!updatedPost) {
            updatedPost = await Post.findByIdAndUpdate(idOrSlug, updateData, {
                new: true,
                runValidators: true,
            });
        }

        if (!updatedPost) {
            return res.status(404).json({
                success: false,
                error: 'Blog post does not exist',
            });
        }

        res.json({
            success: true,
            data: updatedPost,
        });
    } catch (error) {
        console.error('Post update error:', error);
        res.status(500).json({
            success: false,
            error: error.message || 'Server Error',
        });
    }
});

// DELETE /api/posts/:idOrSlug - Delete a blog post by ID or slug (protected: admin only)
router.delete('/:idOrSlug', fakeAuth, async (req, res) => {
    try {
        const { idOrSlug } = req.params;

        // Try to find by slug first, then by ID
        let deletedPost = await Post.findOne({ slug: idOrSlug });
        
        if (!deletedPost) {
            deletedPost = await Post.findById(idOrSlug);
        }

        if (!deletedPost) {
            return res.status(404).json({
                success: false,
                error: 'Blog post does not exist',
            });
        }

        // Delete image from Cloudinary if it's a Cloudinary URL
        if (deletedPost.featuredImage && deletedPost.featuredImage.includes('cloudinary')) {
            try {
                const publicId = deletedPost.featuredImage.split('/').pop().split('.')[0];
                await cloudinary.uploader.destroy(`blog-app/${publicId}`);
            } catch (err) {
                console.error('Error deleting image from Cloudinary:', err);
            }
        }

        await deletedPost.deleteOne();

        res.json({
            success: true,
            message: 'Blog post deleted successfully',
        });
    } catch (error) {
        console.error(error);
        res.status(500).json({
            success: false,
            error: error.message || 'Server Error',
        });
    }
});

// POST /api/posts/upload - Upload an image to Cloudinary
router.post('/upload', upload.single('image'), async (req, res) => {
    try {
        if (!req.file) {
            return res.status(400).json({
                success: false,
                error: 'No image file provided',
            });
        }

        res.status(200).json({
            success: true,
            data: {
                url: req.file.path,
                publicId: req.file.filename,
            },
        });
    } catch (error) {
        console.error('Image upload error:', error);
        res.status(500).json({
            success: false,
            error: error.message || 'Image upload failed',
        });
    }
});


module.exports = router;